### ISSUE TITLE
installing packages from anaconda

### ISSUE THREAD

**Issue by TejasAvinashShetty** [savankoradiya/Google-Colab-Tutorial#1]
Could you please also give some guidance as to how one could install anaconda packages?

**Comment by TejasAvinashShetty** [comment]
Also, can we use .yml file to build environments directly?

**Comment by savankoradiya** [comment]
Hello @TejasAvinashShetty,
Try this:
!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh
!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
!conda create -y --name myenv
!source activate myenv
!conda install -y pytorch

**Comment by TejasAvinashShetty** [comment]
Thank you very much will try as soon as I get time


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=10.0.21&pv=7.1.2&source=email_footer_2] On Mon, Mar 18, 2019 at 8:17pm, Savan Koradiya < notifications@github.com [notifications@github.com] > wrote:
Hello @TejasAvinashShetty [https://github.com/TejasAvinashShetty] ,
Try this:
!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh [https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh]
!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh
!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
!conda create -y --name myenv
!source activate myenv
!conda install -y pytorch
