### ISSUE TITLE
using sudo in colab

### ISSUE THREAD

**Issue by hakS07** [savankoradiya/Google-Colab-Tutorial#2]
I'm new on dealing with colab
i try to run "sudo" and i don't know how i can enter the password 
i try to write in the blank box but nothing change 
![Capture du 2019-03-22 11-54-47](https://user-images.githubusercontent.com/34586193/54818440-89f8c500-4c99-11e9-9b2e-c3b4268dddb0.png)

**Comment by savankoradiya** [comment]
Hey @essalahsouad You can run commands without "sudo"
 **!apt-get update** or **!pip install numpy**

**Comment by MiniSkoot32** [comment]
@hakS07 google colab does not support sudo commands, only python code or r code
