### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by zszazi** [savankoradiya/Google-Colab-Tutorial#3]
Hey @savankoradiya  I have been doing this repo [github link](https://github.com/zszazi/awesome-collection-of-google-colab-notebooks) which contains some cool google colab notebooks and fortunately I found your repo where you have listed some cool tricks of google colab 
Do you mind pulling a PR of my repo and adding the contents of your readme file into the readme file of my repo [readme](https://github.com/zszazi/awesome-collection-of-google-colab-notebooks/blob/master/README.md)?

https://github.com/zszazi/awesome-collection-of-google-colab-notebooks

Your help is appreciated
🙋‍♂️🙋‍♂️🙋‍♂️

**Comment by savankoradiya** [comment]
Hey @zszazi Sure

**Comment by zszazi** [comment]
Thanks @savankoradiya
