### ISSUE TITLE
Images in colab markdown cell?

### ISSUE THREAD

**Issue by saikiransingh007** [savankoradiya/Google-Colab-Tutorial#5]
how to show images in colab markdown cell.?
am using like...
`<img src='/content/.../confusion_matrix.png' width=300px>`
but it is not showing the image, it shows like this..
![img](https://user-images.githubusercontent.com/41643071/57727831-162ed380-76b0-11e9-841d-5b48f47fc46e.JPG)

can't we see image directly, like in Ipython notebook.?

thank you,
saikiran

**Comment by savankoradiya** [comment]
Hey @saikiransingh007 
Try this ![logo](your image path)

**Comment by saikiransingh007** [comment]
> Hey @saikiransingh007
> Try this ![logo](your image path)

![SAMPLE](https://user-images.githubusercontent.com/41643071/58204861-da70bb00-7cfa-11e9-874d-7c656bb82118.JPG)
I tried this... but does't work... in colab - markdown cell....!

**Comment by savankoradiya** [comment]
Get the shareable link of your image from google drive and then add id name in the link
`<img src="http://drive.google.com/uc?export=view&id=**Add image id here**">`

**Comment by tanny411** [comment]
Is there a better solution? Doesn't seem feasible to upload all images I am ever going to use.

**Comment by Droid021** [comment]
Having the same issue, i second @tanny411, linking to images doesn't have to be this complicated

**Comment by nmodem2k** [comment]
![alt text](https://drive.google.com/uc?export=view&id= your image id)
This working for me

**Comment by ghadesi** [comment]
```
  <img src='https://drive.google.com/uc?export=view&id=**your image id**' width=500px>
  <img src='https://drive.google.com/uc?export=view&id=**your image id**' width=500px>
```

This works and you can insert multiple images beside each other.

<img width="1071" alt="Screen Shot 2021-03-13 at 10 48 08 AM" src="https://user-images.githubusercontent.com/6564410/111022693-9c6deb00-83e9-11eb-9550-c10d2ce5b95e.png">

**Comment by JisaVarghese** [comment]
> ```
>   <img src='https://drive.google.com/uc?export=view&id=**your image id**' width=500px>
>   <img src='https://drive.google.com/uc?export=view&id=**your image id**' width=500px>
> ```
> 
> This works and you can insert multiple images beside each other.
> 
> <img alt="Screen Shot 2021-03-13 at 10 48 08 AM" width="1071" src="https://user-images.githubusercontent.com/6564410/111022693-9c6deb00-83e9-11eb-9550-c10d2ce5b95e.png">

this worked for me
